export const AUTH_PASSWORD_MIN_LENGTH = 8
export const AUTH_PASSWORD_MAX_LENGTH = 128

export const USERNAME_MIN_LENGTH = 3
export const USERNAME_MAX_LENGTH = 32
export const PROFILE_DESCRIPTION_MAX_LENGTH = 1000

export const COURSE_TITLE_MAX_LENGTH = 120
export const COURSE_TEXT_MAX_LENGTH = 1000
export const COURSE_PROMPT_MAX_LENGTH = 2000
export const COURSE_TOPIC_MAX_LENGTH = 120
export const COURSE_TOPICS_MAX_COUNT = 20

export const PUBLIC_COURSE_SEARCH_MAX_LENGTH = 120
