AUTH_PASSWORD_MIN_LENGTH = 8
AUTH_PASSWORD_MAX_LENGTH = 128
AUTH_LOGIN_PASSWORD_MIN_LENGTH = 1

USERNAME_MIN_LENGTH = 3
USERNAME_MAX_LENGTH = 32
PROFILE_DESCRIPTION_MAX_LENGTH = 1000

COURSE_TITLE_MAX_LENGTH = 120
COURSE_TEXT_MAX_LENGTH = 1000
COURSE_PROMPT_MAX_LENGTH = 2000
COURSE_TOPIC_MAX_LENGTH = 120
COURSE_TOPICS_MAX_COUNT = 20
PUBLIC_COURSE_SEARCH_MAX_LENGTH = 120

TEST_QUESTIONS_MIN_COUNT = 10
TEST_QUESTIONS_MAX_COUNT = 24
SINGLE_CHOICE_OPTIONS_MIN = 2
SINGLE_CHOICE_OPTIONS_MAX = 6
MULTIPLE_CHOICE_OPTIONS_MIN = 3
MULTIPLE_CHOICE_OPTIONS_MAX = 9
